version: '3'

services:
  front:
    container_name: front
    build: front/.
    volumes:
      - ./front/.:/app
    ports:
      - 4200:4200
      - 49153:49153
  api:
    container_name: api
    build: django_api/.
    volumes:
      - ./django_api/.:/code
      - ./media/:/media-gallery
    ports:
      - "8080:8080"
