name: "Python tests"

on:
  push:
    branches: [ master ]
    # paths:
      # Run the jobs only if there's a file of API that's modified
    #  - django_api/api/*.py
  pull_request:
    branches: [ master ]
    # paths:
      # Run the jobs only if there's a file of API that's modified
    #  - django_api/api/*.py

jobs:
  python-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'code'
        
    - name: Checkout the latest commit to have the code
      run: |
        /usr/bin/git checkout $GITHUB_SHA

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
  debug:
    needs: [python-setup]
    runs-on: ubuntu-latest
    steps:
      - name: What's their values?
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
      - name: ls GITHUB_WORKSPACE
        run: |
          ls -a $GITHUB_WORKSPACE | xargs echo
      - name: ls GITHUB_WORKSPACE/code
        run: |
          ls -a $GITHUB_WORKSPACE/code | xargs echo
      - name: ls HOME
        run: |
          ls -a $HOME | xargs echo
      - name: echo GITHUB_SHA
        run: |
          echo $GITHUB_SHA

  pylint:
    needs: python-setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $GITHUB_WORKSPACE/code
    steps:
    - name: Lint with pylint
      run: |
        python ./lint.py --path ./api/ --threshold 9 --rcfile api/.pylintrc

  unittest:
    needs: python-setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $GITHUB_WORKSPACE/code
    steps:
    - name: Run unittests
      run: |
        python ./manage.py test
